// This file is generated by Slice Machine. Update with care!

import AboutMe from './AboutMe';
import Contact from './Contact';
import Home from './Home';
import Work from './Work';

export {
	AboutMe,
	Contact,
	Home,
	Work,
};

export const components = {
	about_me: AboutMe,
	contact: Contact,
	home: Home,
	work: Work,
};
