// This file is generated by Slice Machine. Update with care!

import AboutMe from './AboutMe';
import Home from './Home';

export {
	AboutMe,
	Home,
};

export const components = {
	about_me: AboutMe,
	home: Home,
};
